name: Postman Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  postman-tests:
    runs-on: ubuntu-latest
    container:
      image: postman/newman_alpine33
      options: --entrypoint /bin/sh

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Newman tests
        run: |
          newman --version
          npm install -g newman-reporter-html
          newman run trello-tasks.postman_collection.json \
            --reporters cli,html \
            --reporter-html-export report.html

      - name: Upload test report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: newman-report
          path: report.html
